export const targetGuide = {
  precedence: "elementId, locator, coordinates",
  tabId: "Chrome tab ID; omitted uses the active tab.",
  frameId: "Chrome frame ID; omitted uses the top frame.",
  documentId: "Document ID from a frame snapshot when available.",
  elementId: "In-memory element ID from the latest snapshot or query.",
  locator: "selector, xpath, text/exactText, role/name, label, placeholder, and zero-based nth.",
  x: "Selected-frame viewport x coordinate for browser/DOM engines; OS-screen x for explicit native actions.",
  y: "Selected-frame viewport y coordinate for browser/DOM engines; OS-screen y for explicit native actions.",
  nativeFallback: "Automatic routing never reinterprets a supplied web target or pointer coordinates as OS-screen coordinates; request engine native explicitly for OS coordinates.",
  mutationFallback: "Automatic routing stops after a mutating engine may have emitted side effects; only an unhandled engine, an exact pre-action target-resolution failure, or a read-only failure can fall through or retry safely.",
} as const;

export const categoryParameterGuides = {
  pointer: "target identifies a point/element; params.button is left|middle|right or back|forward, with optional modifiers[], finite durationMs/clickIntervalMs totaling at most 60000ms, destination ActionTarget, toX, and toY. DOM variants use HTMLElement.click or untrusted synthetic mouse events; browser/native variants generate input.",
  scroll: "params: finite amount or x/y or deltaX/deltaY, behavior instant|smooth, durationMs 0..60000, steps 1..1000; native directional amount is an integer from 1 to 1000 and derived native wheel ticks are capped at 1000; target selects a scrollable element when relevant.",
  touch: "target point/element; params: durationMs 0..60000, steps/moves at most 1000, up to 32 points, pressure, radiusX/Y, tiltX/Y, twist, tangentialPressure, phase, button/buttons; touch gestures use paired toX/toY destinations, and active pen move/end accept a paired finite targetless toX/toY destination. Aggregate requested delay is at most 60000ms.",
  keyboard: "params: normalized common Chromium key/shortcut/aliases, modifiers[], text up to 10000 characters, count 1..1000, finite intervalMs with at most 60000ms requested delay; unknown multi-character key names fail before input. composeText also accepts commit.",
  text: "target must be a compatible enabled text-editing input, textarea, or contenteditable element; readonly targets support focus and selection but not mutation. setValue requires params.value and insert/append/replace require params.text, including explicit empty strings. Named text mutations preflight the resulting JSON-encoded UTF-8 scalar against the 6MiB value budget before DOM or browser input. Current-caret/selection edits and target-bearing undo/redo non-activatingly focus and revalidate the exact target before browser input, while untargeted undo/redo use current focus. Selection actions return only observed target-relative ranges, with start/end/count bounded to 0..1000, plus position and direction forward|backward where applicable.",
  form: "target exact enabled form control; focusField/blurField accept enabled non-hidden input, textarea, select, or button controls and verify activeElement state. Browser/DOM check and radio actions validate input type and return observed checked state, increment/decrement require writable number inputs with steps 1..1000 and return observed value, and submit/reset require form-associated controls. DOM set* actions require their matching writable input type, prevalidate type/range constraints, and return the retained canonical value. Every option token must resolve to exactly one enabled option before mutation; deselection or multiple values require a multi-select.",
  files: "set/clear target an enabled input[type=file], enforce the multiple cardinality, and verify the observed FileList count; browser-device paths use files[] and DOM byte payloads use {name,mimeType,base64}[]; drop targets and completion waits use their explicit fields.",
  drag: "target is source; params.destination is an ActionTarget; data is MIME-to-string; effectAllowed and dropEffect are optional.",
  inspect: "target or locator selects elements; query-all accepts limit; property/style reads use name or properties[].",
  dom: "target selects an element; createElement returns a detached elementId; append/move/clone use source/destination ActionTarget and position; all id/class/className/classList writes and structural removal of identifier-bearing trees are rejected.",
  script: "params.expression is a side-effect-free expression; world MAIN|ISOLATED; CSS actions require exact css and optional origin USER|AUTHOR/allFrames.",
  events: "target element; params.type is required; standard EventInit fields and serializable custom detail are supported.",
  tabs: "target.tabId or params.tabId/tabIds; creation/navigation use url; move uses index/windowId; groups accept group update properties.",
  navigation: "target.tabId; params.url for goto, bypassCache where supported.",
  windows: "params.windowId or target tab; create/update fields follow chrome.windows; movement accepts tabIds.",
  frames: "target.tabId/frameId/documentId; frame reads accept operation document|text|html|selection|query and selector.",
  wait: "request timeoutMs bounds the wait; sleep requires params.durationMs; filters include URL/text/value/attribute/network/download fields and pollIntervalMs/stableMs.",
  clipboard: "write accepts text, html, or items with MIME data as text/base64; read accepts formats[] and returns MIME data; native fallback is text-only; copy/cut/paste operate on current focus/selection.",
  downloads: "start accepts Chrome download options; pause/resume/cancel/remove use downloadId; listDownloads and eraseDownload accept a DownloadQuery in params.query or params; waits accept state/filenameContains/urlContains.",
  screenshot: "target tab/element; params format png|jpeg, quality, rect/scale where directly supplied; results return dataUrl and pixel dimensions, with clip or tile metadata where applicable.",
  capture: "start requires captureId and supports mediaConstraints/recorderOptions/timeslice; stop requires captureId and filename.",
  cookies: "params follows chrome.cookies getAll/get/set/remove details, including partitionKey where supported.",
  storage: "params key/value or database/store/key/value, cache/url/body/headers, storage area, or browsing-data origin/options.",
  network: "request filters use requestId/tab/method/type/phase/status/urlContains; rules follow DNR; fetch accepts url/method/headers/body/responseType.",
  page: "getPageState is immediate; observePage accepts sinceRevision to wait for the next revision.",
  media: "target media element; params time, volume, rate, enabled, or caption index.",
  browserData: "params follow history/bookmark/session/reading-list operations; destructive clears require explicit data/options.",
  compound: "Compound-specific shapes are returned in actionParameterOverrides.",
  nativeUI: "OS-screen target or params x/y; dialogs accept paths/path, decision/tabCount, shortcut, text, and timing fields.",
} as const;
