export {
  MAX_STAGED_UPLOAD_BYTES, MAX_STAGED_UPLOAD_BYTES_PER_OWNER,
  MAX_UPLOAD_SESSIONS, MAX_UPLOAD_SESSIONS_PER_OWNER,
} from "../protocol/limits.js";
export const DEFAULT_RELAY_PORT = 32145;
export const DEFAULT_ACTION_TIMEOUT_MS = 60_000;
export const MAX_WS_MESSAGE_BYTES = 64 * 1024 * 1024;
export const MAX_WS_INBOUND_MESSAGE_BYTES = 2 * 1024 * 1024;
export const MAX_WS_OUTBOUND_QUEUE_BYTES = MAX_WS_MESSAGE_BYTES * 2;
export const MAX_WS_OUTBOUND_QUEUE_MESSAGES = 64;
export const MAX_NATIVE_INPUT_BYTES = 64 * 1024 * 1024;
export const MAX_NATIVE_OUTPUT_BYTES = 1024 * 1024;
export const MAX_NATIVE_CLIPBOARD_OUTPUT_BYTES = 768 * 1024;
export const MAX_TRANSFER_CHUNK_BYTES = 512 * 1024;
export const DEFAULT_TRANSFER_CHUNK_BYTES = 384 * 1024;
export const MAX_DOWNLOAD_SESSIONS = 128;
export const MAX_DOWNLOAD_SESSIONS_PER_OWNER = 32;
export const RELAY_HANDSHAKE_TIMEOUT_MS = 10_000;
export const RELAY_HEARTBEAT_INTERVAL_MS = 20_000;
export const RELAY_PONG_TIMEOUT_MS = 10_000;
export const MAX_NATIVE_CHORD_KEYS = 32;
export const MAX_NATIVE_SHORTCUT_CHARACTERS = 1_024;
export const NATIVE_INPUT_YIELD_INTERVAL = 32;
export const MAX_UPLOAD_CHUNKS_PER_SESSION = 32_768;
export const MAX_UPLOAD_CHUNKS_PER_OWNER = 65_536;
export const MAX_UPLOAD_CHUNKS = 131_072;
export const DEFAULT_MOUSE_SPEED = 1200;
export const DEFAULT_KEY_DELAY_MS = 20;
export const DEFAULT_SLOW_KEY_DELAY_MS = 55;
export const UPLOAD_LEASE_TIMEOUT_MS = 5 * 60_000;
export const COMPLETED_UPLOAD_RETENTION_MS = 30 * 60_000;
export const DIRECTORY_GROUP_ASSEMBLY_RETENTION_MS = 24 * 60 * 60_000;
export const DIRECTORY_GROUP_MAX_ASSEMBLY_MS = 7 * 24 * 60 * 60_000;
export const STAGING_ROOT_STALE_MS = 7 * 24 * 60 * 60_000;
export const RELAY_NETWORK_ADDRESS_ENV = "BROWSER_USE_RELAY_NETWORK_ADDRESS";
