import type { ActionDefinition } from "../actionDefinition.js";

const browser = ["browser"] as const;

export const browserControlActions = [
  { name: "getRuntimeCapabilities", category: "browserData", engines: browser, readOnly: true, description: "Report the current browser platform, manifest, relay state, and unavailable gated browser APIs without claiming page content access." },
  { name: "listTabs", category: "tabs", engines: browser, readOnly: true, description: "List controllable tabs." },
  { name: "getActiveTab", category: "tabs", engines: browser, readOnly: true, description: "Read the active tab." },
  { name: "newTab", category: "tabs", engines: browser, readOnly: false, description: "Create a tab." },
  { name: "closeTab", category: "tabs", engines: browser, readOnly: false, description: "Close a tab while preserving the final browser tab." },
  { name: "activateTab", category: "tabs", engines: browser, readOnly: false, description: "Activate a tab." },
  { name: "switchTab", category: "tabs", engines: browser, readOnly: false, description: "Switch to a tab." },
  { name: "navigateTab", category: "tabs", engines: browser, readOnly: false, description: "Navigate a tab to a URL." },
  { name: "reloadTab", category: "tabs", engines: browser, readOnly: false, description: "Reload a tab." },
  { name: "duplicateTab", category: "tabs", engines: browser, readOnly: false, description: "Duplicate a tab." },
  { name: "moveTab", category: "tabs", engines: browser, readOnly: false, description: "Move a tab within or between windows." },
  { name: "pinTab", category: "tabs", engines: browser, readOnly: false, description: "Pin a tab." },
  { name: "unpinTab", category: "tabs", engines: browser, readOnly: false, description: "Unpin a tab." },
  { name: "groupTabs", category: "tabs", engines: browser, readOnly: false, description: "Group tabs." },
  { name: "ungroupTabs", category: "tabs", engines: browser, readOnly: false, description: "Remove tabs from groups." },
  { name: "muteTab", category: "tabs", engines: browser, readOnly: false, description: "Mute a tab." },
  { name: "unmuteTab", category: "tabs", engines: browser, readOnly: false, description: "Unmute a tab." },
  { name: "zoomIn", category: "tabs", engines: browser, readOnly: false, description: "Increase tab zoom." },
  { name: "zoomOut", category: "tabs", engines: browser, readOnly: false, description: "Decrease tab zoom." },
  { name: "resetZoom", category: "tabs", engines: browser, readOnly: false, description: "Reset tab zoom." },
  { name: "goto", category: "navigation", engines: browser, readOnly: false, description: "Navigate the target tab." },
  { name: "back", category: "navigation", engines: browser, readOnly: false, description: "Go back in tab history." },
  { name: "forward", category: "navigation", engines: browser, readOnly: false, description: "Go forward in tab history." },
  { name: "reload", category: "navigation", engines: browser, readOnly: false, description: "Reload the target tab." },
  { name: "hardReload", category: "navigation", engines: browser, readOnly: false, description: "Reload while bypassing cache where supported." },
  { name: "stopLoading", category: "navigation", engines: browser, readOnly: false, description: "Stop page loading through CDP." },
  { name: "getNavigationState", category: "navigation", engines: browser, readOnly: true, description: "Read navigation and redirect state." },
  { name: "listWindows", category: "windows", engines: browser, readOnly: true, description: "List browser windows." },
  { name: "createWindow", category: "windows", engines: browser, readOnly: false, description: "Create a browser window." },
  { name: "closeWindow", category: "windows", engines: browser, readOnly: false, description: "Close a browser window." },
  { name: "focusWindow", category: "windows", engines: browser, readOnly: false, description: "Focus a browser window." },
  { name: "resizeWindow", category: "windows", engines: browser, readOnly: false, description: "Resize a browser window." },
  { name: "repositionWindow", category: "windows", engines: browser, readOnly: false, description: "Reposition a browser window." },
  { name: "minimizeWindow", category: "windows", engines: browser, readOnly: false, description: "Minimize a browser window." },
  { name: "maximizeWindow", category: "windows", engines: browser, readOnly: false, description: "Maximize a browser window." },
  { name: "restoreWindow", category: "windows", engines: browser, readOnly: false, description: "Restore a browser window." },
  { name: "fullscreenWindow", category: "windows", engines: browser, readOnly: false, description: "Fullscreen a browser window." },
  { name: "moveTabToWindow", category: "windows", engines: browser, readOnly: false, description: "Move tabs between windows." },
  { name: "listFrames", category: "frames", engines: browser, readOnly: true, description: "Enumerate the current frame tree." },
  { name: "executeInFrame", category: "frames", engines: browser, readOnly: true, description: "Run a read-only operation in one frame." },
  { name: "executeInAllFrames", category: "frames", engines: browser, readOnly: true, description: "Run a read-only operation in permitted frames." },
  { name: "findInFrame", category: "frames", engines: ["dom"], readOnly: true, description: "Find a target in a selected frame." },
] satisfies readonly ActionDefinition[];
