import type { ActionDefinition } from "../actionDefinition.js";

const inspect = ["dom"] as const;

export const inspectionActions = [
  { name: "snapshot", category: "inspect", engines: inspect, readOnly: true, description: "Build a page and element catalog without marking the live DOM." },
  { name: "querySelector", category: "inspect", engines: inspect, readOnly: true, description: "Find the first CSS selector match." },
  { name: "querySelectorAll", category: "inspect", engines: inspect, readOnly: true, description: "Find all CSS selector matches." },
  { name: "queryXPath", category: "inspect", engines: inspect, readOnly: true, description: "Find elements with XPath." },
  { name: "queryText", category: "inspect", engines: inspect, readOnly: true, description: "Find exact or partial visible text." },
  { name: "queryRole", category: "inspect", engines: inspect, readOnly: true, description: "Find elements by ARIA role and accessible name." },
  { name: "queryLabel", category: "inspect", engines: inspect, readOnly: true, description: "Find controls by associated label." },
  { name: "queryPlaceholder", category: "inspect", engines: inspect, readOnly: true, description: "Find controls by placeholder." },
  { name: "queryCoordinates", category: "inspect", engines: inspect, readOnly: true, description: "Find elements at viewport coordinates." },
  { name: "traverse", category: "inspect", engines: inspect, readOnly: true, description: "Traverse parents, children, and siblings." },
  { name: "getBoundingBox", category: "inspect", engines: inspect, readOnly: true, description: "Read target bounds." },
  { name: "getElementState", category: "inspect", engines: inspect, readOnly: true, description: "Read visibility, enabled, readonly, checked, and selection state." },
  { name: "getText", category: "inspect", engines: inspect, readOnly: true, description: "Read rendered target text." },
  { name: "getHTML", category: "inspect", engines: inspect, readOnly: true, description: "Read target HTML." },
  { name: "getAttribute", category: "inspect", engines: inspect, readOnly: true, description: "Read a target attribute." },
  { name: "getProperty", category: "inspect", engines: inspect, readOnly: true, description: "Read a serializable target property." },
  { name: "getClasses", category: "inspect", engines: inspect, readOnly: true, description: "Read target classes without changing them." },
  { name: "getComputedStyle", category: "inspect", engines: inspect, readOnly: true, description: "Read selected computed style values." },
  { name: "getFocusedElement", category: "inspect", engines: inspect, readOnly: true, description: "Read the focused element." },
  { name: "setText", category: "dom", engines: inspect, readOnly: false, description: "Replace target text without changing element identifiers." },
  { name: "setHTML", category: "dom", engines: inspect, readOnly: false, description: "Replace target markup while rejecting identifier changes." },
  { name: "setAttribute", category: "dom", engines: inspect, readOnly: false, description: "Set a non-identifier target attribute." },
  { name: "removeAttribute", category: "dom", engines: inspect, readOnly: false, description: "Remove a non-identifier target attribute." },
  { name: "setProperty", category: "dom", engines: inspect, readOnly: false, description: "Set a non-identifier target property." },
  { name: "setStyle", category: "dom", engines: inspect, readOnly: false, description: "Set inline style properties without changing classes." },
  { name: "createElement", category: "dom", engines: inspect, readOnly: false, description: "Create a detached element for later insertion." },
  { name: "appendElement", category: "dom", engines: inspect, readOnly: false, description: "Insert a created element at a target position." },
  { name: "removeElement", category: "dom", engines: inspect, readOnly: false, description: "Detach a target element." },
  { name: "moveElement", category: "dom", engines: inspect, readOnly: false, description: "Move a target element to a destination." },
  { name: "cloneElement", category: "dom", engines: inspect, readOnly: false, description: "Clone a target with optional safe insertion." },
  { name: "callMethod", category: "dom", engines: inspect, readOnly: false, description: "Call a target method while rejecting identifier mutation." },
  { name: "evaluateReadOnly", category: "script", engines: ["browser"], readOnly: true, description: "Evaluate with CDP side effects forbidden." },
  { name: "evaluate", category: "script", engines: ["browser"], readOnly: true, description: "Evaluate an expression with side effects forbidden in MAIN or ISOLATED world." },
  { name: "evaluateOnElement", category: "script", engines: ["browser"], readOnly: true, description: "Evaluate side-effect-free code with the exact resolved target as element across permitted frames and open shadow roots." },
  { name: "evaluateInFrame", category: "script", engines: ["browser"], readOnly: true, description: "Evaluate a side-effect-free expression in a permitted frame." },
  { name: "injectCSS", category: "script", engines: ["browser"], readOnly: false, description: "Inject CSS without changing page element identifiers or classes." },
  { name: "removeInjectedCSS", category: "script", engines: ["browser"], readOnly: false, description: "Remove an exact previously injected CSS string." },
  { name: "dispatchEvent", category: "events", engines: ["dom"], readOnly: false, description: "Dispatch a requested DOM event without changing element identifiers." },
  { name: "dispatchCustomEvent", category: "events", engines: ["dom"], readOnly: false, description: "Dispatch an application event with serializable detail." },
] satisfies readonly ActionDefinition[];
